// Nombres públicos compatibles con clientes Android, iOS y administración.
export const OPERACIONES = {
  emitirCheques: "emitirCheques",
  gestionarCheque: "gestionarCheque",
  cobrarCheque: "cobrarCheque",
  procesarCheques: "procesarCheques",
  solicitarAsesor: "solicitarAsesor",
  responderAsesoria: "responderAsesoria",

  registrarCliente: "registrarCliente",
  solicitarCredito: "solicitarCredito",
  solicitarTarjetaCredito: "solicitarCredito",
  elegirCorteTarjeta: "elegirCorteTarjeta",
  consultarTarjetaCredito: "consultarTarjetaCredito",
  registrarConsumoTarjeta: "registrarConsumoTarjeta",
  pagarTarjetaCredito: "pagarTarjetaCredito",
  procesarCortesTarjetas: "procesarCortesTarjetas",
  solicitarFisica: "solicitarFisica",
  revisarTarjeta: "revisarTarjeta",
  abrirAhorros: "abrirAhorros",
  destinatario: "destinatario",
  transferir: "transferir",
  guardarContacto: "guardarContacto",
  guardarTarjeta: "guardarTarjeta",
  pagarExterno: "pagarExterno",
  guardarSolicitud: "guardarSolicitud",
  registrarDocumento: "registrarDocumento",
  enviarSolicitud: "enviarSolicitud",
  consultarFactura: "consultarFactura",
  pagarServicio: "pagarServicio",
  configurarAutopago: "configurarAutopago",
  pausarAutopago: "pausarAutopago",
  ajustar: "ajustar",
  migrarCuentas: "migrarCuentas",
  revisarSolicitud: "revisarSolicitud",
  guardarServicio: "guardarServicio",
  guardarDecoracion: "guardarDecoracion",
  procesarAutopagos: "procesarAutopagos",
};
